set hidden

set nowrap      " don't wrap lines
set tabstop=4       " a tab is four spaces
set backspace=indent,eol,start  "allow backspacing over everything in insert mode
set autoindent      " always set autoindenting on
set copyindent      " copy the previous indentation on autoindenting
set nonumber      " dont always show line numbers
set shiftwidth=2    " number of spaces to use for autoindenting
set shiftround      " use multiple of shiftwidth when indenting with '<' and '>'
set showmatch       " set show matching parenthesis
set ignorecase      " ignore case when searching
set smartcase       " ignore case if search pattern is all lowercase, case-sensitive otherwise
set smarttab        " insert tabs on the start of a line according to shiftwidth, not tabstop
set hlsearch        " highlight search terms
set incsearch       " show search matches as you type

set history=1000    " remember more commands and search history
set undolevels=1000 " use many more levels of undo
set wildignore=*.swp,*.bak,*.pyc,*.class
set title           " change the terminal's title
set visualbell      " don't beep
set noerrorbells    " don't beep

set nobackup
set noswapfile
set ruler
set cursorline      " underline the current line, for quick orientation

filetype plugin indent on

nnoremap <F8> :setl noai nocin nosi inde=<CR>

if v:version >= 730
  set undofile      " keep a persistent backup file
  set undodir=~/.vim/.undo,~/tmp,/tmp
endif

highlight DiffAdd term=reverse cterm=bold ctermbg=green ctermfg=white 
highlight DiffChange term=reverse cterm=bold ctermbg=cyan ctermfg=black 
highlight DiffText term=reverse cterm=bold ctermbg=gray ctermfg=black 
highlight DiffDelete term=reverse cterm=bold ctermbg=red ctermfg=black

